### ISSUE TITLE
GetColumnFamily() call in C#

### ISSUE THREAD

**Issue by rapoth** [warrenfalk/rocksdb-sharp#12]
I have a couple of somewhat trivial questions so please excuse my ignorance. I see a call in C# [GetColumnFamily()](https://github.com/warrenfalk/rocksdb-sharp/blob/368db05e2a4c19ce15dcba1705d5c19102098cd2/shared/RocksDb.cs#L205) that I cannot see in the [CPP implementation](https://github.com/facebook/rocksdb/blob/v5.2.1/include/rocksdb/db.h).

I have a couple of clarification questions:

1. What is the expected behavior if the column family cannot be found? Instead of throwing an exception (since you do _return columnFamilies[name];_), does it make sense to return null or do you expect the application to handle the exception?
2. Since this call is not in the CPP implementation, what is your general take on API parity between CPP and C#? 

Thank you!

**Comment by warrenfalk** [comment]
According to the [documentation](https://github.com/facebook/rocksdb/wiki/Column-Families) of the CPP implementation, a CPP user must be sure "to delete all ColumnFamilyHandles before you delete your DB pointer."

This is problematic in the C# implementation and so to allow for a slightly more idiomatic C# implementation, the Db instance keeps track of the ColumnFamilyHandles and you get access to them via that dictionary.  The Db will then ensure they are disposed of before it is disposed itself.

The way column families work in the CPP implementation requires you to list the column families when opening the database, and then the database open will return the handles for those column families.  In the C# implementation, the Db instance does this for you and so it needs to expose those handles to you.  It does this via the dictionary.

So GetColumnFamily() is returning the handles that correspond to the list of ColumnFamilyOptions you passed in when opening the database, and not the full list of ColumnFamilies within the database itself.  That is what list_column_families() is for, which [we should expose in the high level as you noted](https://github.com/warrenfalk/rocksdb-sharp/issues/11).

That said, I have no problem with GetColumnFamily() being modified to return null instead of throwing an exception.

As far as feature parity, I would like to be able to support everything in this library that can be done with the CPP library, but so far, that isn't possible because only a subset is exposed via the C API, which C# must use.  And even then, I haven't gotten around to implementing the lesser used features in the C API that I haven't had a use for.  I'd consider PRs for these if someone needed them.

As for API parity, I was originally aiming at mimicking the Java API, but have since settled on aiming for more idiomatic C# where possible.

Does that answer your questions?
