### ISSUE TITLE
Any chance for NuGet in near future?

### ISSUE THREAD

**Issue by jakoss** [warrenfalk/rocksdb-sharp#2]
Like in title, is there any chance you'll release this as a nuget package soon? 

PS. Library is great, keep up the good work ;)

**Comment by warrenfalk** [comment]
I've only held off because it's still in a state of flux with potentially breaking changes in the near future, but I could probably get the process started by publishing a beta.  I'm using it in a production application already, which itself is only in what I'd call an alpha stage, so it's starting to stabilize, but I still find an occasional design flaw that results in a breaking change.

I will see about getting a beta out either today or in the next couple of days.

**Comment by warrenfalk** [comment]
Thought I'd leave an update on this.  I spent a small amount of time trying to get a nuget package working for this but ran into problems with getting the native binaries to be included in the project correctly and copied as content to the output.  So I still need to do some more work on that.  I know that other projects wrapping native binaries manage to do this with some success, so I may try to see how they do it.

**Comment by jakoss** [comment]
Well, LMDB (https://github.com/CoreyKaylor/Lightning.NET) used to do this (stable version), but now they don't (beta version). Not sure why, that's just my observation.

**Comment by warrenfalk** [comment]
OK, now available [on NuGet](https://www.nuget.org/packages/RocksDbSharp/).

It is split into two packages.  Install both [RocksDbSharp](https://www.nuget.org/packages/RocksDbSharp/) and [RocksDbNative](https://www.nuget.org/packages/RocksDbNative/) if you want to get going quickly or create a self-contained package.

Install RocksDbSharp alone if the native binaries will already be installed on the target system and you want to avoid including the extra 15 MB or so of native binaries.

**Comment by paramr** [comment]
Thanks!
