### ISSUE TITLE
ColumnFamilyHandle design is too confusing and requires special knowledge to avoid AccessViolations

### ISSUE THREAD

**Issue by jakoss** [warrenfalk/rocksdb-sharp#3]
I'm using iterator to create enumerator like that:

```
internal class MetadataEnumerator : IEnumerator<Tuple<long, long>>
            {
                private Iterator _iterator;
                private ColumnFamilyHandle _metadataColumn;

                public MetadataEnumerator(RocksDb dbContext)
                {
                    _metadataColumn = dbContext.GetColumnFamily("metadata");
                    _iterator = dbContext.NewIterator(_metadataColumn);
                    _iterator.SeekToFirst();
                }

                public void Dispose()
                {
                    _metadataColumn.Dispose();
                    _iterator.Dispose();
                }

                public bool MoveNext()
                {
                    _iterator.Next();
                    return _iterator.Valid();
                }

                public void Reset()
                {
                    _iterator.SeekToFirst();
                }

                public Tuple<long, long> Current
                {
                    get
                    {
                        Byte[] key = _iterator.Key();
                        Byte[] value = _iterator.Value();
                        return new Tuple<long, long>(BitConverter.ToInt64(key, 0), BitConverter.ToInt64(value, 0));
                    }
                }

                object IEnumerator.Current
                {
                    get { return Current; }
                }
            }
```

But i'm getting AccessViolation line `_iterator = dbContext.NewIterator(_metadataColumn);` is hit for the second time. You might have any idea how can i bypass this?

**Comment by jakoss** [comment]
I figured out that disposing `ColumnFamilyHandle _metadataColumn` caused an error, but i still don't know exactly why is that happening. From code https://github.com/warrenfalk/rocksdb-sharp/blob/master/ColumnFamilyHandle.cs i can see that in Dispose only cf handle is getting destroyed.

**Comment by warrenfalk** [comment]
You are correct.

My guess is that you are thinking that there is one "Column Family" and you can have many "Column Family Handles" to that Column Family, and that you get a new "handle" every call to `GetColumnFamily()` and that you should dispose every one.  That is understandable given the names.  

But this isn't actually how that works.  Before opening the database, you have to create every `ColumnFamilyHandle` one time and those same `ColumnFamilyHandle` instances then reused throughout the lifetime of the database and are what is being returned by `GetColumnFamily()`.  You should in fact never dispose of them because the database (`RocksDb` instance) will do it.

Your code fails the next time you use the `dbContext.GetColumnFamily("metadata")` because you already disposed it.  So you should _not_ match calls to GetColumnFamily() with a Dispose().

I may try to think of a way to help make that a little more intuitive, but it's tricky.  The problem is that this is how the RocksDb C API works.  In C++, it uses `shared_ptr`s and so it has reference counters to control lifetime.  The C API doesn't.  And so it becomes tricky to try to keep track of whether a database is actually using a column family handle or not.  I don't think it is valid to try to use a column family handle in more than one database, so I might be able to split that class into two classes - one that defines the column family and doesn't need to be disposed and a second which is managed internally so you don't have to worry about it.

I will leave this issue open to consider that.

**Comment by jakoss** [comment]
Thanks for explanation :)

**Comment by warrenfalk** [comment]
I have separated ColumnFamilyHandle into a public interface and an internal class to help to eliminate this mistake in the future.
