### ISSUE TITLE
Unable to load DLL 'libc'

### ISSUE THREAD

**Issue by raphac** [warrenfalk/rocksdb-sharp#48]
Hello
I currently have the following error message:
`Unable to load DLL 'libc': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`
`System.DllNotFoundException:
   at NativeImport.Importers+PosixImporter.uname (RocksDbSharp, Version=5.4.6.10, Culture=neutral, PublicKeyToken=null)
   at NativeImport.Importers+PosixImporter.GetPlatform (RocksDbSharp, Version=5.4.6.10, Culture=neutral, PublicKeyToken=null)
   at NativeImport.Importers+PosixImporter..ctor (RocksDbSharp, Version=5.4.6.10, Culture=neutral, PublicKeyToken=null)
   at NativeImport.Importers..cctor (RocksDbSharp, Version=5.4.6.10, Culture=neutral, PublicKeyToken=null)
   at NativeImport.Auto.Import (RocksDbSharp, Version=5.4.6.10, Culture=neutral, PublicKeyToken=null)
   at RocksDbSharp.Native..cctor (RocksDbSharp, Version=5.4.6.10, Culture=neutral, PublicKeyToken=null)
   at RocksDbSharp.OptionsHandle..ctor (RocksDbSharp, Version=5.4.6.10, Culture=neutral, PublicKeyToken=null)`
I run it on a windows machine.
At first I thought that it is a problem with the OS. I logged the values and the result was:
`Environment.OSVersion.Platform: Win32NT`. So it should take the `Importers.Windows`. I think the problem is somewere in the method [public static T Import<T>](https://github.com/warrenfalk/rocksdb-sharp/blob/8818ab4e7917877a99f6f1b25791bc1f29679a9a/RocksDbSharp/AutoNativeImport.cs#L209) Method. Does anyone have an idea what the problem could be?
Thanks a lot!

**Comment by davidgallegolobato** [comment]
I am facing the same issue, any movement?

Thanks.

**Comment by warrenfalk** [comment]
The stack trace above shows that it is using the PosixImporter.  This suggests that IsOSPlatform() returns true for OSPlatform.OSX or OSPlatform.Linux, but this function is in a builtin library.  Do you have any more information about the environment you're running it in?  I can't reproduce it.  If you have can create a minimum project to reproduce it, and give me as much information about the environment you can... I'll take a look.

**Comment by davidgallegolobato** [comment]
Thanks for your reply.

Here it is a bit of my context:

- I am running rocksdb on two type of machines: Windows 10 ones (.NET Framework 4.6.2) and linux boxes with .NET Core.
- So far it has worked without any issues with .NET Core and all compilations of Rocksdb (I assume because we are using the static library).
- Some Windows 10 machines are having this issue mentioned here.
- All Windows machines are quite similar: VS 2017 (15.7.4) with VC+ Redistributable 2017 (14.14.25405.0)

RocksDB compilation:
- Initially I compiled rocksdb version 5.12.4 with CMakeList, some windows machines having issues.
- I have tried a newer version of RocksDB 5.15.4 and vcpckg and now other machines are facing the same issue, but different ones. So basically, some compilation of Rocksdb work in some machines and other in different ones. Besides, other Windows 10 machines don't have any issue at all. When there is an issue, it is always unable to load DLL 'libc'.

I cannot figure out what dependency is causing the issue.

Thanks.


EDITED: I am compiling RocksDB with LZ4 compression following the documentation.

**Comment by warrenfalk** [comment]
The stack trace suggests that the problem occurs when the constructor of PosixImporter is run which calls GetPlatform() which calls uname() which is an extern within libc.

However, in the code (below) you can see that this happens within a try catch
```csharp
            static string GetPlatform()
            {
                IntPtr buf = IntPtr.Zero;
                try
                {
                    buf = Marshal.AllocHGlobal(8192);
                    return (0 == uname(buf)) ? Marshal.PtrToStringAnsi(buf) : "Unknown";
                }
                catch
                {
                    return "Unknown";
                }
                finally
                {
                    if (buf != IntPtr.Zero)
                        Marshal.FreeHGlobal(buf);
                }
            }
```

So I don't know what's going on here.  I don't know why this would behave differently from one Windows machine to the next.

I can say that it shouldn't make a difference what version of the native rocksdb library you're using - this error occurs prior to loading it.  So VC redistributable doesn't mater either.

I think that the native importers should be created lazily, though; we have no reason to create a Posix importer in a windows environment.  Then the problem should go away, I think.  I can't verify since I still can't reproduce it.

**Comment by warrenfalk** [comment]
I've pushed a 5.4.6.11 version of RocksDbSharp with this change to nuget.  See if that version resolves this issue.

**Comment by davidgallegolobato** [comment]
Thanks for your help.

After a new compilation of rocksdb with vcpckg, I have discovered that is related to some framework incompatibility. Basically we were using an old dependency library in version .netfx 4.0. Once in 4.6 (same version of our component using rocksdb) and using the compilation done with vcpckg, the problem goes away and works in all machines.

When I have some spare time I will dig into it to understand why this only caused issues with RocksDB.

Thanks.
