### ISSUE TITLE
DotNet 4.0 support

### ISSUE THREAD

**Issue by elbandi** [warrenfalk/rocksdb-sharp#8]
Can you make support 4.0 framework? Yes, thats old. But some old projects cannot/want to switch to 4.5, but need a good key-value storage.

**Comment by warrenfalk** [comment]
This will take some work.  The problem is that all of the API changes to ease the transition to .Net Core were made in 4.5.  So it is a minor inconvenience to create a single code base for both 4.5 and Core, but a major inconvenience to target both 4.0 and Core as this requires either duplicating a lot of code with minor modifications or copious amounts `#if #else` blocks.

It might be possible to hack something that works and doesn't pollute the existing code too badly.  I will take a look at it.

**Comment by warrenfalk** [comment]
Should work now with 4.13.2.1 published to nuget
